---
name: Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - 'apply'
          - 'destroy'

jobs:
  plan_and_apply:
    uses: ${organization_name}/${repository_name_templates}/${cd_template_path}@main
    name: '${name} CD'
    permissions:
      id-token: write
      contents: read
    with:
      terraform_action: $${{ inputs.terraform_action }}
      root_module_folder_relative_path: '${root_module_folder_relative_path}'
      azure_client_id: "$${{ vars.${azure_client_id} }}"
      azure_subscription_id: "$${{ vars.${azure_subscription_id} }}"
      azure_tenant_id: "$${{ vars.${azure_tenant_id} }}"
      backend_azure_resource_group_name: "$${{ vars.${backend_azure_resource_group_name} }}"
      backend_azure_storage_account_name: "$${{ vars.${backend_azure_storage_account_name} }}" 
      backend_azure_storage_account_container_name: "$${{ vars.${backend_azure_storage_account_container_name} }}"
