---
name: Continuous Integration
on:
  pull_request:
    branches:
      - main
    paths:
      - '${root_module_folder_relative_path}/**'
      - 'modules/**'
  workflow_dispatch:

jobs:
  validate_and_plan:
    uses: ${organization_name}/${repository_name_templates}/${ci_template_path}@main
    name: '${name} CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      root_module_folder_relative_path: '${root_module_folder_relative_path}'
      environment_name_plan: '${environment_name_plan}'
      environment_name_apply: '${environment_name_apply}'
